###
GET localhost:38085/v1/transactions/batches/history?limit=10&page=0&order=-1&status=dispatched
Accept: application/json

###

POST localhost:38085/v1/transactions/stress
Accept: application/json

###